name: Not2Late
favicon: null
layout_spectrum: 0.9533139341510832
typography_spectrum: 0.8053437012713403
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9a4c0c'
    - '#e2a353'
    - '#1d150a'
    - '#fffffd'
    - '#ffd07b'
  brandStrength: 0.7234444834757596
  lightness: 0.9375
  saturation: 0.9375
  rhythmicContrast: 0.25
purpose: []
